### ISSUE TITLE
geoservice lacks base path

### ISSUE THREAD

**Issue by vainiusd** [lafernando/ballerina-cloud-native-middleware-workshop#1]
Hi,

trying to run the programs after the workshop locally.
http resource is not found until this is put into geo_service.bal:

```
@http:ServiceConfig {
    basePath: "/"
}
```

If I remember that correctly, you did it manually when typing apps.

**Comment by lafernando** [comment]
Hi,

Yes, using that annotation you can change the base path to "/". So then the final endpoint URL would be "http://localhost:8080/geoip/{ip}", in the current way that is there in the repo, it is "http://localhost:8080/geoservice/geoip/{ip}". By default the base path picks up the name of the service. 

Cheers,
Anjana.

**Comment by vainiusd** [comment]
Thanks for the explanation!
